### ISSUE TITLE
Theme raises lots of errors on macOS

### ISSUE THREAD

**Issue by douglasstarnes** [syncfusion/essential-ui-kit-for-xamarin.forms#27] opened 2019-12-06 16:40 UTC
I started to follow the Holiday Challenge instructions and everything worked fine on Windows.  However, the LightTheme.xaml file raises errors on just about every line, 281 to be exact.  This happened just after adding the Login and Onboarding forms from the UI kit.  Cleaning and rebuilding the solution did nothing.

**Comment by MeikandaNayanar** [comment] 2019-12-09 11:21
Hi Douglasstarnes,

 

Thank you for contacting us.

 

We cannot reproduce the reported issue at our end. So, we have created a sample by adding the _Login_ and _Onboarding_ screens with our Visual Studio for MAC extension and attached the sample in the below link.

 

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Sample-564190474


Please try this sample and let us know whether this helps. Still, if you are facing any issues with this sample, please provide the following details to us, which will be helpful for us to provide you with a better solution. Attaching the sample application that you are facing the issue will be more helpful.



1. Visual Studio version
2. Xamarin.Forms version
3. Syncfusion components version
4. Any specific device configuration 

Please let us know if you have any questions.
 

Regards,

Meikandan

**Comment by douglasstarnes** [comment] 2019-12-14 16:02
I am using Visual Studio for Mac version 8.3.10 Build 2 with Xamarin.Forms version 4.4.0.991265.

The issue seems to be that only the LightTheme.xaml.cs file is included in the project.  The LightTheme.xaml file is generated but not included in the project.  Manually adding LightTheme.xaml solves the problem.

**Comment by MeikandaNayanar** [comment] 2019-12-18 04:05
Hi @douglasstarnes 

Thank you for your update.

This is a known-issue that we have reported to Visual Studio for MAC development team. Please refer to the below issue report that we have logged to the Visual Studio community.

https://github.com/mhutch/MonoDevelop.AddinMaker/issues/78

So we have to solve this kind of problem manually until the above-mentioned bug is fixed in Visual Studio for MAC. 

I am closing the bug report with the details above. Please do not hesitate to open a new thread if you face any other problems in the future.

Thanks
Meikandan

**Closed by MeikandaNayanar** 2019-12-18 04:05 UTC
