### ISSUE TITLE
No embeddedresource found for EssentialUIKit.App

### ISSUE THREAD

**Issue by b0uch3** [syncfusion/essential-ui-kit-for-xamarin.forms#7] opened 2019-09-13 18:46 UTC
Trying to run demo on iphone device (ios 13.1 beta 3) and receiving error on startup.

Not sure if this is an iOS beta issue and if I need to change a build setting for iOS project.

**Comment by MeikandaNayanar** [comment] 2019-09-17 10:43
Hi @b0uch3 

Thank you for contacting us.

We have tried to reproduce the issue that you have mentioned, but unfortunately, we could not reproduce it while running the ‘EssentialUIKit’ project from this repository. We could deploy and run the ‘EssentialUIKit.iOS’ source without any issues.  As you say the issue is reproduced when trying to build itself, can you clean and rebuild the project once again? 

Please let us know if the issue still exists from your end even after rebuilding the application. 

Thanks,
Meikandan

**Comment by MeikandaNayanar** [comment] 2019-09-23 07:09
Hi @b0uch3 

Please let us know if you could give some more details to reproduce the issue? Now I am closing this ticket now. Please do not hesitate to re-open or create a new one in the future. 

Thanks,
Meikandan

**Comment by b0uch3** [comment] 2019-09-25 18:52
Sorry, I haven't had a chance to try and run the samples again.   will reach out again when I do, and if I run into a problem.

**Comment by awaescher** [comment] 2019-10-04 07:57
Hi,

I just cloned the repository and hit run:

<img width="1573" alt="Screenshot 2019-10-04 at 09 52 13" src="https://user-images.githubusercontent.com/3630638/66190588-a932cf00-e68c-11e9-9cf7-dc380bb12775.png">
 
## System
macOS Mojave 10.14.6 (18G95)
Xcode Version 11.0 (11A420a)
Visual Studio for Mac 8.3.1 (build 18)

## Output
```
Resolved pending breakpoint for 'Xamarin.HotReload.HotReloadAgent.BreakpointCheckpoint()' to [0x0](no debug symbols).
2019-10-04 09:55:44.754538+0200 EssentialUIKit.iOS[15287:3066262] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=15287
2019-10-04 09:55:44.757621+0200 EssentialUIKit.iOS[15287:3066262] SecTaskCopyDebugDescription: EssentialUIKit.i[15287]/0#-1 LF=0
2019-10-04 09:55:44.763786+0200 EssentialUIKit.iOS[15287:3066262] SecTaskLoadEntitlements failed error=22 cs_flags=200, pid=15287
2019-10-04 09:55:44.763986+0200 EssentialUIKit.iOS[15287:3066262] SecTaskCopyDebugDescription: EssentialUIKit.i[15287]/0#-1 LF=0
Resolved pending breakpoint at 'AppDelegate.cs:34,1' to bool EssentialUIKit.iOS.AppDelegate.FinishedLaunching (UIKit.UIApplication app, Foundation.NSDictionary options) [0x00001].

```

## Callstack
```
Xamarin.Forms.Xaml.XamlLoader.Load(EssentialUIKit.App view, System.RuntimeType callingType) in D:/a/1/s/Xamarin.Forms.Xaml/XamlLoader.cs:69
Xamarin.Forms.Xaml.Extensions.LoadFromXaml<EssentialUIKit.App>(EssentialUIKit.App view, System.RuntimeType callingType) in D:/a/1/s/Xamarin.Forms.Xaml/ViewExtensions.cs:36
EssentialUIKit.App.InitializeComponent() in /Users/daw/Source/essential-ui-kit-for-xamarin.forms/EssentialUIKit/obj/Debug/netstandard2.0/App.xaml.g.cs:21
EssentialUIKit.App..ctor() in /Users/daw/Source/essential-ui-kit-for-xamarin.forms/EssentialUIKit/App.xaml.cs:34
EssentialUIKit.iOS.AppDelegate.FinishedLaunching(UIKit.UIApplication app, Foundation.NSDictionary options) in /Users/daw/Source/essential-ui-kit-for-xamarin.forms/EssentialUIKit.iOS/AppDelegate.cs:35
UIKit.UIApplication.UIApplicationMain() in 
UIKit.UIApplication.Main(string[] args, System.IntPtr principal, System.IntPtr delegate) in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:86
UIKit.UIApplication.Main(string[] args, string principalClassName, string delegateClassName) in /Library/Frameworks/Xamarin.iOS.framework/Versions/13.2.0.42/src/Xamarin.iOS/UIKit/UIApplication.cs:65
EssentialUIKit.iOS.Application.Main(string[] args) in /Users/daw/Source/essential-ui-kit-for-xamarin.forms/EssentialUIKit.iOS/Main.cs:12
```

**Comment by b0uch3** [comment] 2019-10-04 12:21
bingo! same.

**Comment by gregmag** [comment] 2019-10-10 20:07
The same for me too. No solution ?

**Comment by b0uch3** [comment] 2019-10-10 21:37
I wish I could re-open the issue.  this issue may need to be resubmitted with reference to this original.

**Comment by MeikandaNayanar** [comment] 2019-10-11 04:05
Hi @b0uch3 / @gregmag ,

Thank you for the details. I have now reopened the issue.

We are now working on providing a solution for this issue and will update this thread once we found one.

Thanks,
Meikandan

**Comment by MeikandaNayanar** [comment] 2019-10-29 08:51
Hi @b0uch3 / @gregmag / @awaescher ,

We have now resolved an issue related to this XamlParserException as for the mentioned scenario, can you please update and check the source? Please revert us if you could still reproduce the issue after updating the soucre.

Thanks
Meikandan

**Comment by MeikandaNayanar** [comment] 2019-11-05 05:26
Hi @b0uch3 / @gregmag / @awaescher ,

I hope the problem is resolved now. Now I'm going to close this ticket. Please do not hesitate in the future to reopen or create a new one.

Thanks,
Meikandan

**Closed by MeikandaNayanar** 2019-11-05 05:26 UTC
