### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by Erdogan34** [syncfusion/essential-ui-kit-for-xamarin.forms#28] opened 2019-12-11 21:14 UTC
Hello, 

Defined BaseImageURL in App.xaml is not accessible.
https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/

When the application is working, seems a blank page.

**Comment by MeikandaNayanar** [comment] 2019-12-18 04:07
Hi @Erdogan34 

Thank you for contacting us. 
 
We are checking the possible scenarios that might cause this at your end. In the meanwhile, can you please check the below link from your browser and update us whether this link gets you the image. So that we can confirm that this is not any network firewall issues.  
 
https://cdn.syncfusion.com/essential-ui-kit-for-xamarin.forms/common/uikitimages/Image1.png 

Please let us know if you need any other assistance in this.

Thanks
Meikandan

**Comment by MeikandaNayanar** [comment] 2020-04-08 06:12
Hi @Erdogan34 

I hope the issue is now resolved at your end. We are closing this ticket now, please feel free to open a new thread for any other requirements or queries.

Thanks
Meikandan

**Closed by MeikandaNayanar** 2020-04-08 06:12 UTC
